-- AlterTable
ALTER TABLE `ProjectFile` MODIFY `category` ENUM(
  'PLC',
  'HMI',
  'ROBOT',
  'ELECTRICAL',
  'MECHANICAL',
  'PNEUMATIC',
  'DOCUMENT',
  'PHOTO_VIDEO',
  'BACKUP',
  'COMMISSIONING',
  'SERVICE'
) NOT NULL;

-- AlterTable
ALTER TABLE `ActivityLog` MODIFY `action` ENUM(
  'LOGIN',
  'LOGOUT',
  'LOGIN_FAILED',
  'PROJECT_CREATED',
  'PROJECT_UPDATED',
  'PROJECT_ARCHIVED',
  'PROJECT_DELETED',
  'FILE_UPLOADED',
  'ELECTRICAL_UPLOADED',
  'MECHANICAL_UPLOADED',
  'DOCUMENT_UPLOADED',
  'FILE_DOWNLOADED',
  'FILE_DELETED',
  'VERSION_CREATED',
  'SERVICE_RECORD_ADDED',
  'COMMISSIONING_RECORD_ADDED',
  'PERMISSION_DENIED',
  'USER_CREATED',
  'USER_UPDATED',
  'USER_DISABLED',
  'USER_ENABLED',
  'USER_PASSWORD_RESET',
  'USER_DELETED'
) NOT NULL;
