-- AlterTable
ALTER TABLE `User` ADD COLUMN `fullName` VARCHAR(160) NULL AFTER `username`;

-- AlterTable
ALTER TABLE `ActivityLog` MODIFY `action` ENUM(
  'LOGIN',
  'LOGOUT',
  'LOGIN_FAILED',
  'PROJECT_CREATED',
  'PROJECT_UPDATED',
  'PROJECT_ARCHIVED',
  'PROJECT_DELETED',
  'FILE_UPLOADED',
  'FILE_DOWNLOADED',
  'FILE_DELETED',
  'VERSION_CREATED',
  'SERVICE_RECORD_ADDED',
  'COMMISSIONING_RECORD_ADDED',
  'PERMISSION_DENIED',
  'USER_CREATED',
  'USER_UPDATED',
  'USER_DISABLED',
  'USER_PASSWORD_RESET',
  'USER_DELETED'
) NOT NULL;
